In [55]:
!pip install xgboost

   ---------------------------------------- 0.0/124.9 MB ? eta -:--:--
   ---------------------------------------- 0.1/124.9 MB 1.7 MB/s eta 0:01:16
   ---------------------------------------- 0.6/124.9 MB 8.1 MB/s eta 0:00:16
   ---------------------------------------- 1.2/124.9 MB 9.9 MB/s eta 0:00:13
    --------------------------------------- 2.1/124.9 MB 13.5 MB/s eta 0:00:10
    --------------------------------------- 3.1/124.9 MB 13.9 MB/s eta 0:00:09
   - -------------------------------------- 3.8/124.9 MB 15.2 MB/s eta 0:00:08
   - -------------------------------------- 4.6/124.9 MB 15.5 MB/s eta 0:00:08
   - -------------------------------------- 5.4/124.9 MB 16.3 MB/s eta 0:00:08
   -- ------------------------------------- 6.3/124.9 MB 16.7 MB/s eta 0:00:08
   -- ------------------------------------- 7.2/124.9 MB 17.1 MB/s eta 0:00:07
   -- ------------------------------------- 8.2/124.9 MB 16.8 MB/s eta 0:00:07
   -- ------------------------------------- 8.9/124.9 MB 17.1 M

In [3]:
#import nessasary packages
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    accuracy_score, confusion_matrix, classification_report, roc_auc_score, roc_curve
)

In [9]:
# Import data
df = pd.read_csv(r'C:\Users\36476\Downloads\Diabetes Date.csv')
df

Age        BMI     Glucose  Diabetes
0     58  29.249533  173.648398         0
1     71  29.033358   89.489266         0
2     48  35.562494   99.802681         0
3     34  32.299206  163.892834         1
4     62  33.443271  163.604750         0
..   ...        ...         ...       ...
495   69  36.067661  107.916135         0
496   44  20.433898  160.347645         0
497   43  36.621950  181.815912         1
498   32  20.804751  171.380629         1
499   79  26.740320   75.150447         1

[500 rows x 4 columns]

In [11]:
# Split into train & test
X = df.drop('Diabetes', axis=1)
y = df['Diabetes']

In [13]:
#diplay X
X

Age        BMI     Glucose
0     58  29.249533  173.648398
1     71  29.033358   89.489266
2     48  35.562494   99.802681
3     34  32.299206  163.892834
4     62  33.443271  163.604750
..   ...        ...         ...
495   69  36.067661  107.916135
496   44  20.433898  160.347645
497   43  36.621950  181.815912
498   32  20.804751  171.380629
499   79  26.740320   75.150447

[500 rows x 3 columns]

In [15]:
#display y
y

0      0
1      0
2      0
3      1
4      0
      ..
495    0
496    0
497    1
498    1
499    1
Name: Diabetes, Length: 500, dtype: int64

In [17]:
#Split the data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [19]:
# Train a Random Forest Classifier
clf = RandomForestClassifier(n_estimators=100, random_state=42)
clf.fit(X_train, y_train)

# Predictions
y_pred = clf.predict(X_test)
y_pred_proba = clf.predict_proba(X_test)  # Probability predictions for ROC curve


In [21]:
#calculate accurcy score
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.2f}")
#calculate accurcy using confusion matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", cm)
#Precision, Recall, F1-Score
print("Classification Report:\n", classification_report(y_test, y_pred))

Accuracy: 0.63
Confusion Matrix:
 [[61  5]
 [32  2]]
Classification Report:
               precision    recall  f1-score   support

           0       0.66      0.92      0.77        66
           1       0.29      0.06      0.10        34

    accuracy                           0.63       100
   macro avg       0.47      0.49      0.43       100
weighted avg       0.53      0.63      0.54       100



In [25]:
#import decision Tree 
from sklearn.tree import DecisionTreeClassifier
# # Train Decision Tree
dt_model = DecisionTreeClassifier(max_depth=5, random_state=42)
dt_model.fit(X_train, y_train)
#predictions
dt_pred = dt_model.predict(X_test)
dt_proba = dt_model.predict_proba(X_test)[:, 1]

In [27]:
#calculate accurcy score for decision tree
accuracy = accuracy_score(y_test, dt_pred)
print(f"Accuracy: {accuracy:.2f}")
#calculate accurcy using confusion matrix
cm = confusion_matrix(y_test, dt_pred)
print("Confusion Matrix:\n", cm)
#Precision, Recall, F1-Score
print("Classification Report:\n", classification_report(y_test, dt_pred))

Accuracy: 0.65
Confusion Matrix:
 [[63  3]
 [32  2]]
Classification Report:
               precision    recall  f1-score   support

           0       0.66      0.95      0.78        66
           1       0.40      0.06      0.10        34

    accuracy                           0.65       100
   macro avg       0.53      0.51      0.44       100
weighted avg       0.57      0.65      0.55       100



In [29]:
#Import Logistic Regression
from sklearn.linear_model import LogisticRegression
# Train Logistic Regression
logistic_model = LogisticRegression()
logistic_model.fit(X_train, y_train)
logistic_pred = logistic_model.predict(X_test)
logistic_proba = logistic_model.predict_proba(X_test)[:, 1]

In [43]:
#calculate accurcy score for Logistic Regression
accuracy = accuracy_score(y_test, logistic_pred)
print(f"Accuracy: {accuracy:.2f}")
#calculate accurcy of Logistic Regression using confusion matrix
cm = confusion_matrix(y_test, logistic_pred)
print("Confusion Matrix:\n", cm)
#Precision, Recall, F1-Score
print("Classification Report:\n", classification_report(y_test, logistic_pred))

Accuracy: 0.66
Confusion Matrix:
 [[66  0]
 [34  0]]
Classification Report:
               precision    recall  f1-score   support

           0       0.66      1.00      0.80        66
           1       0.00      0.00      0.00        34

    accuracy                           0.66       100
   macro avg       0.33      0.50      0.40       100
weighted avg       0.44      0.66      0.52       100



C:\Users\36476\AppData\Local\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\36476\AppData\Local\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\36476\AppData\Local\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result)

In [31]:
#import SVM
from sklearn.svm import SVC
# SVM Model
svm_model = SVC(probability=True, random_state=42)
svm_model.fit(X_train, y_train)
svm_pred = svm_model.predict(X_test)
svm_proba = svm_model.predict_proba(X_test)[:, 1]

In [49]:
#calculate accurcy score for SVM
accuracy = accuracy_score(y_test,svm_pred)
print(f"Accuracy: {accuracy:.2f}")
#calculate accurcy of SVM using confusion matrix
cm = confusion_matrix(y_test,svm_pred)
print("Confusion Matrix:\n", cm)
#Precision, Recall, F1-Score
print("Classification Report:\n", classification_report(y_test,svm_pred))

Accuracy: 0.66
Confusion Matrix:
 [[66  0]
 [34  0]]
Classification Report:
               precision    recall  f1-score   support

           0       0.66      1.00      0.80        66
           1       0.00      0.00      0.00        34

    accuracy                           0.66       100
   macro avg       0.33      0.50      0.40       100
weighted avg       0.44      0.66      0.52       100



C:\Users\36476\AppData\Local\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\36476\AppData\Local\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\36476\AppData\Local\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result)

In [33]:
#import XGBoost
from xgboost import XGBClassifier
# XGBoost Model
xgb_model = XGBClassifier(use_label_encoder=False, eval_metric='logloss', random_state=42)
xgb_model.fit(X_train, y_train)
xgb_pred = xgb_model.predict(X_test)
xgb_proba = xgb_model.predict_proba(X_test)[:, 1]

C:\Users\36476\AppData\Local\anaconda3\Lib\site-packages\xgboost\core.py:158: UserWarning: [12:40:04] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-08cbc0333d8d4aae1-1\xgboost\xgboost-ci-windows\src\learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


In [35]:
#calculate accurcy score for XGBoost
accuracy = accuracy_score(y_test,xgb_pred)
print(f"Accuracy: {accuracy:.2f}")
#calculate accurcy of XGBoost using confusion matrix
cm = confusion_matrix(y_test,xgb_pred)
print("Confusion Matrix:\n", cm)
#Precision, Recall, F1-Score
print("Classification Report:\n", classification_report(y_test,xgb_pred))

Accuracy: 0.61
Confusion Matrix:
 [[54 12]
 [27  7]]
Classification Report:
               precision    recall  f1-score   support

           0       0.67      0.82      0.73        66
           1       0.37      0.21      0.26        34

    accuracy                           0.61       100
   macro avg       0.52      0.51      0.50       100
weighted avg       0.57      0.61      0.57       100



In [37]:
# Combine actual and predicted values for all models for testing a DataFrame
prediction_results = X_test.copy()
prediction_results['Actual'] = y_test.values
prediction_results['Predicted_LR'] = logistic_pred
prediction_results['Predicted_SVM'] = svm_pred
prediction_results['Predicted_xgb'] = xgb_pred
# Save to Excel in following pathfolder
output_path = r'C:\Users\36476\Downloads\Diabetes_prediction.xlsx'
prediction_results.to_excel(output_path, index=False)
